### ISSUE TITLE
Cannot get stats from a remote db host

### ISSUE THREAD

**Issue by lklepner** [pm2-hive/pm2-mongodb#2]
It looks like the IP value is applied when initially testing the connection -
https://github.com/pm2-hive/pm2-mongodb/blob/42640ee8bd924d1597696c3da9243b65ad99106a/app.js

But not when querying for stats going forward -
https://github.com/pm2-hive/pm2-mongodb/blob/522491da384a9f789a57d8f14d192ebf1c0c0154/lib/mongostat.js

I submitted a pull request which I believe addresses this -
https://github.com/pm2-hive/pm2-mongodb/pull/4

**Comment by alavit-d** [comment]
Merged, will update on npm soon. Thanks for the fix :)
