### ISSUE TITLE
Fail: could not retrieve mongostat metrics 2

### ISSUE THREAD

**Issue by marspark** [pm2-hive/pm2-mongodb#6]
Hi

I've installed the "pm2-mongodb" module however it shows N/A for everything except CPU and MEM. 

I've checked with pm2 logs and it keep says "pm2-mongodb-5 Fail: could not retrieve mongostat metrics 2". 

I've confirmed that mongostat is working.

![screen shot 2015-12-23 at 6 56 56 pm](https://cloud.githubusercontent.com/assets/4025346/11975693/6be9e48e-a9ab-11e5-80c0-a42e0bf68ab5.png)

**Comment by Necromos** [comment]
1. Make sure that you have installed mongostats on machine.
2. Try to add whitespace before authenticationDatabase field (you need to do this in machine console via `pm2 set pm2-mongodb:authenticationDatabase " dbname"`). I made patch for this and it is waiting for pull.

**Comment by marspark** [comment]
Hi,

I've ran 

```
pm2 set pm2-mongodb:authenticationDatabase "wokamon"
```

and it didn't work. Please advise.

Thanks!

**Comment by Necromos** [comment]
Try
`pm2 set pm2-mongodb:authenticationDatabase " wokamon"`

**Comment by AussieFlem** [comment]
Having the same issue on Ubuntu, MongoDB v3.0.8.
mongostat (not mongostat_s_) is installed.
User has "clusterMonitor" role.

Is this a v3 issue?

**Comment by alavit-d** [comment]
Hey, I just merged the @Necromos contribution and published the latest on NPM. Sorry for the delay!
I tested with Mongodb v3.0.7 and saw no issue, could you try with the latest version?

**Comment by AussieFlem** [comment]
Yep - N/A's are gone, stats are showing and the repeated auth fail message is gone from the logs.

Looks to have done the trick - nice catch @Necromos

**Comment by marspark** [comment]
It works now, thank you :D
