### ISSUE TITLE
Show is the server is Primary/Secondary in case of a replica set setup.

### ISSUE THREAD

**Issue by spaceadserver** [pm2-hive/pm2-mongodb#9]
It's very important to alert in a replica set setup which server is acting as Primary/Secondary.

**Comment by soyuka** [comment]
#10

**Comment by alavit-d** [comment]
Fixed ee6fb010d24d174e53bf1624753cb6b2424fc10b: If a replica set setup is detected, will print the replica set  name and the status: `PRIMARY`/`SECONDARY`/`UNKNOWN`
